services:
  web1:
    build:
      context: ./web1
      dockerfile: ./Dockerfile.web
    expose:
      - "80"
    volumes:
      - ./web1/web:/usr/share/nginx/html/web
      - ./web1/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web1/logs:/var/log/app
    depends_on:
      - php1
      - worker1
    restart: unless-stopped

  worker1:
    build:
      context: ./web1
      dockerfile: ./Dockerfile.worker
    volumes:
      - ./web1/scripts:/opt/app/scripts
      - ./web1/logs:/var/log/app
      - ./:/hostfs:ro
      - /proc:/host/proc:ro
      - ./web1/web:/opt/app/web
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: monitoring
      DB_USER: monitor
      DB_PASS: monitor_pass
    depends_on:
      - php1
      - db
    restart: unless-stopped

  php1:
    image: php:8.2-fpm-alpine
    volumes:
      - ./web1/web:/usr/share/nginx/html/web
      - ./web1/logs:/var/log/app
    restart: unless-stopped

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - web1

  web2:
    build:
      context: ./web2/
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html
      - ./web2/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: monitoring-postgres
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor_pass
      POSTGRES_DB: monitoring
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
